import assert from 'node:assert/strict';
import { createServer } from 'vite';
const server=await createServer({optimizeDeps:{noDiscovery:true,include:[]},server:{middlewareMode:true,hmr:false},appType:'custom'});
try {
  const {Graph}=await server.ssrLoadModule('/src/kg/graph.ts');
  const {emptyMaintenance,prepareMaintenance,createMaintenanceTool,assertMaintenanceMergeAllowed}=await server.ssrLoadModule('/src/glossary-maintenance.ts');
  const {makeLexiconAsset,parseLexiconAsset,replacementPipeline}=await server.ssrLoadModule('/src/lexicon-transfer.ts');
  const {applyAutoReplace,emptySttLexicon}=await server.ssrLoadModule('/src/stt-lexicon.ts');
  const graph=Graph.empty();
  const a=graph.getOrCreate('garden-planner','A calendar for community garden planting.');
  const b=graph.getOrCreate('garden-planning','An independent volunteer training program.');
  const maintenance=emptyMaintenance(); prepareMaintenance(graph,maintenance);
  assert.equal(maintenance.pending.length,1);
  const tool=createMaintenanceTool({graph,state:maintenance,assertActive:()=>{},record:()=>{},onMerge:()=>{}});
  await tool.execute('decision',{operation:'distinct',ids:maintenance.pending[0].ids,reason:'The user distinguishes the calendar from the training program.'});
  const stt={mistranscriptions:[],autoReplace:[{from:'API file',to:'api file',exactCase:true,ts:'fixture'}]};
  const legacyPipeline={'buffers':{present:false},'stt-lexicon':{present:false},'flags':{present:false},'running-context':{present:false}};
  const saved={graph:{present:true,value:graph.serialize()},pipeline:{present:true,value:{maintenance,sttLexicon:stt,runningContext:[]}},legacyPipeline,archive:[]};
  const asset=makeLexiconAsset(saved);
  const imported=await parseLexiconAsset(JSON.parse(JSON.stringify(asset)));
  const snapshot=replacementPipeline(imported,7);
  assert.deepEqual(snapshot.maintenance,maintenance,'portable export/import retains binding decisions and their provenance');
  assert.equal(snapshot.generation,7); assert.deepEqual(snapshot.jobs,[]);
  assert.throws(()=>assertMaintenanceMergeAllowed(snapshot.maintenance,a.id,b.id),/binding distinct/);
  imported.graph.getOrCreate(a.label,'A revised planting calendar.');
  prepareMaintenance(imported.graph,snapshot.maintenance);
  assert.equal(snapshot.maintenance.pending.length,0,'description edits cannot reopen imported binding decisions');
  assert.equal(snapshot.sttLexicon.autoReplace[0].exactCase,true);
  assert.equal(applyAutoReplace('API file Api file',snapshot.sttLexicon.autoReplace),'api file Api file');
  const malformed=JSON.parse(JSON.stringify(asset)); malformed.maintenance.decisions[0].before[0].description='Tampered evidence';
  await assert.rejects(parseLexiconAsset(malformed),/Invalid personal glossary/);
  await assert.rejects(parseLexiconAsset({...asset,maintenance:null}),/Invalid personal glossary/);
  await assert.rejects(parseLexiconAsset({...asset,stt:{...stt,autoReplace:[{...stt.autoReplace[0],exactCase:'true'}]}}),/Invalid speech/);
  await assert.rejects(parseLexiconAsset({...asset,stt:{...stt,autoReplace:[{...stt.autoReplace[0],exactCase:false}]}}),/exact_case/);
  const old=await parseLexiconAsset({lexicon_version:1,terms:graph.serialize(),stt:emptySttLexicon(),running_context:[]});
  assert.deepEqual(old.maintenance,emptyMaintenance());assert.deepEqual(old.archive,[]);
  const oldStorage=makeLexiconAsset({...saved,pipeline:{present:false},legacyPipeline:{...legacyPipeline,'stt-lexicon':{present:true,value:stt}}});
  assert.deepEqual(oldStorage.stt,stt);assert.deepEqual(oldStorage.maintenance,emptyMaintenance());
  asset.maintenance.decisions.length=0;
  assert.equal(maintenance.decisions.length,1,'export does not mutate saved state');
  imported.maintenance.decisions.length=0;
  assert.equal(snapshot.maintenance.decisions.length,1,'publication state is independent of the parsed asset');
  console.log('Lexicon transfer regressions passed');
} finally {await server.close();}
